
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make db-update'
	@echo


.PHONY: help


db-update:
	@make -C helper/ db-update
.PHONY: db-update
