THE_GHOME_SHELL_THEME_NAME="vimix-dark-grey"
THE_WM_THEME_NAME="vimix-dark-grey"
THE_GTK_THEME_NAME="vimix-dark-grey"
THE_ICON_THEME_NAME="Colloid-grey-dark"
THE_CURSOR_THEME_NAME="Qogir"
THE_CURSOR_SIZE="24"
