THE_GHOME_SHELL_THEME_NAME="Fluent-round-red-Dark"
THE_WM_THEME_NAME="Fluent-round-red-Dark"
THE_GTK_THEME_NAME="Fluent-round-red-Dark"
THE_ICON_THEME_NAME="Tela-red-dark"
THE_CURSOR_THEME_NAME="Qogir"
THE_CURSOR_SIZE="24"
