THE_GHOME_SHELL_THEME_NAME="WhiteSur-Dark-orange"
THE_WM_THEME_NAME="WhiteSur-Dark-orange"
THE_GTK_THEME_NAME="WhiteSur-Dark-orange"
THE_ICON_THEME_NAME="Colloid-orange-dark"
THE_CURSOR_THEME_NAME="Qogir"
THE_CURSOR_SIZE="24"
