#!/usr/bin/sh
# [Pluma Tool]
# Name=Open terminal here
# Comment=Open a terminal in the document location
# Input=nothing
# Output=output-panel
# Applicability=local
# Save-files=nothing
# Languages=
# Shortcut=F4


#TODO: use "mateconftool-2 -g /desktop/mate/applications/terminal/exec"
mate-terminal --working-directory=$PLUMA_CURRENT_DOCUMENT_DIR &
