#!/usr/bin/env bash


################################################################################
##
## /usr/local/bin/gnome-panel-layout-ctrl-set
##
################################################################################


################################################################################
### Head: Note
##

## * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/project/bin/install.sh

##
### Tail: Note
################################################################################


################################################################################
### Head: Init
##

THE_BASE_DIR_PATH="$(cd -- "$(dirname -- "$0")" ; pwd)"
#THE_PLAN_DIR_PATH="$THE_BASE_DIR_PATH"
#THE_CONFIG_FILE_PATH="${THE_PLAN_DIR_PATH}/demo.conf"
#source "$THE_CONFIG_FILE_PATH"
#. "$THE_CONFIG_FILE_PATH"

##
### Tail: Init
################################################################################


################################################################################
### Head: Util / Debug
##

util_error_echo () {
	echo "$@" 1>&2
}

##
### Head: Util / Debug
################################################################################


################################################################################
### Head: Util / util_chcek_layout_name
##

util_chcek_layout_name () {
	local layout_selected="$1"

	if [ -z "${layout_selected}" ]; then
		layout_selected="default"
	fi

	echo "${layout_selected}"
}

##
### Head: Util / util_chcek_layout_name
################################################################################



################################################################################
### Head: Model / mod_gnome_panel_layout_ctrl_set
##

sys_gnome_panel_set_layout_v1 () {

	local layout_selected="$(util_chcek_layout_name $1)"


	util_error_echo
	util_error_echo "dconf reset -f /org/gnome/gnome-panel/"
	dconf reset -f /org/gnome/gnome-panel/


	util_error_echo
	util_error_echo "gsettings set org.gnome.gnome-panel.general default-layout '${layout_selected}'"
	gsettings set org.gnome.gnome-panel.general default-layout "${layout_selected}"


	util_error_echo
	util_error_echo 'exec gnome-panel --replace &'
	exec gnome-panel --replace &

	util_error_echo

}

sys_gnome_panel_set_layout_v2 () {

	local layout_selected="$(util_chcek_layout_name $1)"


	util_error_echo
	util_error_echo "gsettings set org.gnome.gnome-panel.general default-layout '${layout_selected}'"
	gsettings set org.gnome.gnome-panel.general default-layout "${layout_selected}"


	util_error_echo
	util_error_echo "dconf reset -f /org/gnome/gnome-panel/layout/"
	dconf reset -f /org/gnome/gnome-panel/layout/


	util_error_echo

}


sys_gnome_panel_set_layout () {

	sys_gnome_panel_set_layout_v1 "$1"
	#sys_gnome_panel_set_layout_v2 "$1"

}

mod_gnome_panel_layout_ctrl_set () {

	sys_gnome_panel_set_layout "$1"

}

##
### Tail: Model / mod_gnome_panel_layout_ctrl_set
################################################################################


################################################################################
### Head: Main
##

__main__ () {

	mod_gnome_panel_layout_ctrl_set "$1"

	return 0

}

__main__ "$@"

##
### Tail: Main
################################################################################
