THE_GHOME_SHELL_THEME_NAME="WhiteSur-Dark-yellow"
THE_WM_THEME_NAME="WhiteSur-Dark-yellow"
THE_GTK_THEME_NAME="WhiteSur-Dark-yellow"
THE_ICON_THEME_NAME="Colloid-yellow-dark"
THE_CURSOR_THEME_NAME="Qogir"
THE_CURSOR_SIZE="24"
