
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo
	@echo '	$$ make config-gnome-shell'
	@echo
	@echo '	$$ make config-cinnamon'
	@echo
	@echo '	$$ make config-mate'
	@echo
	@echo '	$$ make config-xfce'
	@echo
	@echo
	@echo '	$$ make asset-install'
	@echo
	@echo '	$$ make asset-cursor-theme'
	@echo
	@echo '	$$ make asset-icon-theme'
	@echo
	@echo '	$$ make asset-gtk-theme'
	@echo
	@echo '	$$ make asset-kde-theme'
	@echo


.PHONY: help


config-gnome-shell:
	@./config-gnome-shell.sh
.PHONY: config-gnome-shell


config-cinnamon:
	@./config-cinnamon.sh
.PHONY: config-cinnamon


config-mate:
	@./config-mate.sh
.PHONY: config-mate


config-xfce:
	@./config-xfce.sh
.PHONY: config-xfce


asset-install:
	@./asset-install.sh
.PHONY: asset-install


asset-cursor-theme:
	@./asset-cursor-theme.sh
.PHONY: asset-cursor-theme


asset-icon-theme:
	@./asset-icon-theme.sh
.PHONY: asset-icon-theme


asset-gtk-theme:
	@./asset-gtk-theme.sh
.PHONY: asset-gtk-theme


asset-kde-theme:
	@./asset-kde-theme.sh
.PHONY: asset-kde-theme

